project_id       = "crosscutdata-509514"
region           = "us-central1"
gke_location     = "us-east1" # Autopilot stockout in us-central1 on 2026-10-04
env              = "dev"
github_owner     = "sdhayanand"
alert_email      = "" # set to get e-mail alerts, e.g. "you@example.com"
enable_gke       = true
enable_cloudsql  = true
enable_scheduler = true
enable_composer  = false # Composer 2 small env ≈ $300+/month; DAGs are tested in CI instead
enable_apigee    = false # Apigee X eval org takes ~1h to provision; enable when you want to demo it
cloudsql_tier    = "db-f1-micro"
